-- CREATE TABLE / DROP
CREATE TABLE TABLE_NAME
(COLUMN1 VARCHAR(10) WITH DEFAULT 'name', 
COLUMN2 DATE NOT NULL WITH DEFAULT '0001-01-01',
COLUMN3 CHAR(1) NOT NULL WITH DEFAULT 'F');

DROP TABLE TABLE_NAME;



-- SESSION 1
CREATE TABLE FRIENDS
(NAME VARCHAR(20) NOT NULL,
AGE SMALLINT,
BIRTHDATE DATE);

CREATE TABLE COUNTRY
(NAME VARCHAR(50) NOT NULL,
CAPITAL VARCHAR(40)NOT NULL,
POPULATION INTEGER DEFAULT 1000000);

CREATE TABLE CARS
(PLATE CHAR(10) NOT NULL,
BRAND VARCHAR(25) NOT NULL,
COLOR VARCHAR(20) NOT NULL,
YEAR SMALLINT NOT NULL,
IS_ELECTRIC BOOLEAN NOT NULL DEFAULT FALSE,
DATE_BOUGHT DATE NOT NULL DEFAULT CURRENT DATE,
DATE_SOLD DATE);

DROP TABLE FRIENDS;
DROP TABLE COUNTRY;
DROP TABLE CARS;