-- SELECT, (AND & OR), ORDER BY, LIMIT
SELECT COLUMN1 
FROM TABLE_NAME
WHERE COLUMN2 = 'CONDITION'
AND COLUMN1 = 'CONDITION'
OR COLUMN1 = 'CONDITION'
ORDER BY COLUMN1 ASC -- DESC
LIMIT 1; -- MAX NUMBER OF ROWS



-- SESSION 3
CREATE TABLE T1 (
C1 INTEGER,
C2 CHAR(10));

SELECT C1, C2
FROM T1;

SELECT *
FROM T1;

SELECT *
FROM T1
WHERE C1 > 5;

SELECT NAME, AGE
FROM STUDENTS
WHERE COUNTRY = 'Germany'
AND AGE < 27;

SELECT *
FROM STUDENTS
WHERE COUNTRY = 'India'
AND AGE > 31;

SELECT *
FROM (SELECT * FROM STUDENTS ORDER BY AGE LIMIT 5)
ORDER BY COUNTRY; -- ORDERING BY AGE AND LIMITING FIRST AND THEN ORDERING BY COUNTRY

SELECT *
FROM STUDENTS
WHERE COUNTRY = 'France' OR COUNTRY = 'Spain'
ORDER BY AGE DESC
LIMIT 5;

INSERT INTO TABLE_1 (COLUMN1, COLUMN2)
VALUES (VALUE1, VALUE2);

UPDATE TABLE_1
SET COLUMN_1 = VALUE3
WHERE COLUMN_1 = VALUE4;

DELETE TABLE_1
COLUMN_1 = VALUE1;

SELECT COLUMNS
FROM TABLE_1
WHERE COLUMN_1 = VALUE1
ORDER BY COLUMNS;