-- HOMEWORK 1
DROP TABLE PRACTICE_STUDENTS;

CREATE TABLE PRACTICE_STUDENTS (
NAME VARCHAR(40) NOT NULL,
AGE SMALLINT,
COUNTRY VARCHAR(20),
GENDER CHAR(1) NOT NULL);

INSERT INTO PRACTICE_STUDENTS VALUES
('Spencer', 23, 'United States', 'M'),
('Seb', 18, 'Germany', 'F'),
('Ryder', 15, 'Italy', 'F'),
('Steve', 60, 'Leave', 'M'),
('Steve', 99, 'Spain', 'F'),
('Steve', 14, 'France', 'M'),
('Steve', 31, 'Canada', 'M');

SELECT *
FROM PRACTICE_STUDENTS
WHERE AGE > 20;

SELECT NAME, AGE
FROM PRACTICE_STUDENTS
WHERE LOWER(COUNTRY) LIKE 'l%';

SELECT *
FROM PRACTICE_STUDENTS
WHERE COUNTRY IN ('Spain', 'France', 'Canada');

SELECT *
FROM PRACTICE_STUDENTS
WHERE AGE < 30 AND LOWER(NAME) LIKE '%p%'

SELECT *
FROM PRACTICE_STUDENTS
WHERE AGE > 25 AND AGE < 35;

SELECT *
FROM PRACTICE_STUDENTS
WHERE NAME LIKE '%a%' OR NAME LIKE '%b%' OR NAME LIKE '%c%';


-- HOMEWORK 2

SELECT NAME, CASE 
	WHEN GENDER = 'M' THEN 'MALE' ELSE 'FEMALE'
END AS GENDER
FROM PRACTICE_STUDENTS
WHERE AGE > 10
ORDER BY GENDER;

SELECT NAME, REPLACE(REPLACE(GENDER, 'M', 'MALE'), 'F', 'FEMALE') AS GENDER
FROM PRACTICE_STUDENTS
WHERE AGE > 10
ORDER BY GENDER;

SELECT EMPNO, COALESCE(PHONENO, '0000') AS PHONE, JOB, CASE
	WHEN GENDER = 'M' THEN 'MALE' ELSE 'FEMALE'
END GENDER
FROM EMPLOYEE
WHERE WORKDEPT LIKE 'E%'
ORDER BY GENDER ASC, JOB ASC;

SELECT EMPNO, COALESCE(PHONENO, '0000') AS PHONE, JOB, CASE
	WHEN GENDER = 'M' THEN 'MALE' ELSE 'FEMALE'
END GENDER
FROM EMPLOYEE
WHERE WORKDEPT LIKE 'E%' AND GENDER LIKE 'F'
ORDER BY EMPNO DESC;

SELECT FIRSTNME, LASTNAME, CASE 
	WHEN 2024 - YEAR(HIREDATE) > 8 THEN 'TOP'
	WHEN 2024 - YEAR(HIREDATE) BETWEEN 5 AND 8 THEN 'SENIOR'
	WHEN 2024 - YEAR(HIREDATE) BETWEEN 3 AND 5 THEN 'JUNIOR'
	ELSE 'NEWBIES'
END AS RANK 
FROM EMPLOYEE
WHERE JOB = 'CONSULTANT'
ORDER BY HIREDATE;

SELECT FIRSTNME||' '||LASTNAME||' is '||
CASE WHEN SUBSTR(JOB,1,1) IN ('A','E','I','O','U')
THEN 'an' ELSE 'a' END||' '||
SUBSTR(JOB,1,1)||LOWER(SUBSTR(JOB,2))||'. '||
CASE WHEN GENDER='F' THEN 'She' ELSE 'He' END ||' is '||
(YEAR(CURRENT DATE) - YEAR(BIRTHDATE))||
' years old and was hired '||
(YEAR(CURRENT DATE) - YEAR(HIREDATE))||' years ago.'
FROM EMPLOYEE;

SELECT FIRSTNME || ' ' || LASTNAME || CASE 
	WHEN PHONENO IS NOT NULL
	THEN '''s phone number is ' || PHONENO || '.'
	ELSE ' hasn''t got a phone number yet.'
END
FROM EMPLOYEE;


-- HOMEWORK 3
SELECT *
FROM PRACTICE_STUDENTS
WHERE LENGTH(COUNTRY) > 5;

SELECT *
FROM PRACTICE_STUDENTS
WHERE LENGTH(COUNTRY) > 5 AND AGE = (SELECT MIN(AGE) FROM PRACTICE_STUDENTS);

SELECT FIRSTNME, SALARY, GENDER
FROM EMPLOYEE
WHERE GENDER = 'F' AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE WHERE GENDER = 'M')
ORDER BY SALARY ASC;

SELECT (NO_PHONES + SHARED) AS PHONES_TO_BUY
FROM (SELECT COUNT(*) AS NUM_ROWS,
COUNT(PHONENO) AS NUM_PHONES,
(COUNT(*) - COUNT(PHONENO)) AS NO_PHONES,
(COUNT(PHONENO)- COUNT(DISTINCT(PHONENO))) SHARED
FROM EMPLOYEE
WHERE YEAR(CURRENT DATE) - YEAR(HIREDATE) >= 5);


-- HOMEWORK 4
SELECT GENDER, COUNT(*)
FROM EMPLOYEE
GROUP BY GENDER;

SELECT WORKDEPT, COUNT(*)
FROM EMPLOYEE
GROUP BY WORKDEPT;

SELECT WORKDEPT, COUNT(*)
FROM EMPLOYEE
WHERE GENDER = 'F'
GROUP BY WORKDEPT;

SELECT WORKDEPT, SUM(SALARY)
FROM EMPLOYEE
WHERE YEAR(CURRENT DATE) - YEAR(HIREDATE) >= 10
GROUP BY WORKDEPT;

SELECT EDLEVEL
FROM EMPLOYEE
GROUP BY EDLEVEL;

SELECT FIRSTNME, COUNT(*)
FROM EMPLOYEE
GROUP BY FIRSTNME;

SELECT COUNT(*)
FROM (SELECT FIRSTNME 
		FROM EMPLOYEE 
		GROUP BY FIRSTNME 
		HAVING COUNT(*) > 1);

SELECT FIRSTNME, COUNT(*)
FROM EMPLOYEE
GROUP BY FIRSTNME
ORDER BY COUNT(*) ASC
LIMIT 3;

SELECT FIRSTNME,COUNT(*)
FROM EMPLOYEE
GROUP BY FIRSTNME
HAVING COUNT(*) = (SELECT COUNT(*)
FROM EMPLOYEE
GROUP BY FIRSTNME
HAVING COUNT(*) > 1
ORDER BY 1
LIMIT 1);

SELECT WORKDEPT, AVG(COALESCE(SALARY, 0) + COALESCE(COMM, 0) + COALESCE(BONUS, 0))
FROM EMPLOYEE
WHERE GENDER = 'F' AND YEAR(BIRTHDATE) BETWEEN 1980 AND 1989 AND JOB = 'OFFICE STAFF'
GROUP BY WORKDEPT;

SELECT WORKDEPT, COUNT(*), AVG(SALARY)
FROM EMPLOYEE
GROUP BY WORKDEPT
HAVING COUNT(*) > 100;



SELECT NAME, LOCATE ('UNITED',UPPER(NAME))
FROM COUNTRIES
WHERE UPPER(NAME) LIKE '%UNITED%';



